version: "3.9"
services:
  #NonSQL database
  mongo:
    build:
      context: ./mongo
      dockerfile: Dockerfile
    image: martin76ec/animixmongo
    container_name: animix_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
  #API
  api_server:
    build:
      context: ./api_server
      dockerfile: Dockerfile
    image: martin76ec/animixapi
    container_name: animix_api
    volumes:
      - "./api_server/api/:/usr/bin/www"
    environment:
      PORT: 9000
    ports:
      - "9000:9000"
  #INTERFACE
  webapp:
    build:
      context: ./webapp
      dockerfile: Dockerfile
    image: martin76ec/animixwebapp
    container_name: animix_webapp
    volumes:
      - "./webapp/app/:/usr/bin/www"
    environment:
      PORT: 9001
    ports:
      - "9001:9001"
